[package]
name = "fingerprinter"
version = "0.1.0"
authors = ["Moritz Wanzenböck <moritz.wanzenboeck@catalysts.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fingerprinter"
path = "src/lib.rs"

[[bin]]
name = "fingerprinter"
path = "src/main.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
